version: '3.8'
services:
  findhome_db:
    image: mysql:latest
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--silent"
        ]
      interval: 30s
      timeout: 300s
      retries: 1000
    environment:
      - MYSQL_ROOT_PASSWORD=RandomPass1.
      - MYSQL_DATABASE=find_home
    ports:
      - "3300:3306"
    volumes:
      - ./migrations/find_home.sql:/docker-entrypoint-initdb.d/find_home.sql
  web:
    image: shahriarkabir/findhome:latest
    environment:
      - jwtSecretAdmin=fgewgwg
      - jwtSecretCompany=qggq
      - jwtSecretUser=gfgr re
      - dbPort=3306
      - dbName=find_home
      - dbUser=root
      - dbPassword=RandomPass1.
      - dbHost=findhome_db
    ports:
      - "4000:4000"
    depends_on:
      findhome_db:
        condition: service_healthy
  ml_server:
    image: shahriarkabir/find_home_ml_server:latest
    ports:
      - "8080:8080"
volumes:
  mysql-data:
