version: '3.8'
services:
  findhome_db:
    image: mysql:latest
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--silent"
        ]
      interval: 10s
      timeout: 20s
      retries: 50
    environment:
      - MYSQL_ROOT_PASSWORD=<MySQL password>
      - MYSQL_DATABASE=find_home
      - MYSQL_USER=root
      - MYSQL_PASSWORD=<MySQL password>
    ports:
      - "3300:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    image: shahriarkabir/findhome
    environment:
      - jwtSecretAdmin=fgewgwg
      - jwtSecretCompany=qggq
      - jwtSecretUser=gfgr re
      - dbPort=3306
      - dbName=find_home
      - dbUser=root
      - dbPassword=<MySQL password>
      - dbHost=findhome_db
    ports:
      - "4000:4000"
    depends_on:
      - findhome_db
  ml_server:
    image: shahriarkabir/find_home_ml_server:latest
    ports:
      - "8080:8080"
volumes:
  mysql-data:
